create table A1_ALUMNO(
DNI NUMBER(8),
NOMBRE VARCHAR2 (30) NOT NULL,
PR_APELLIDO VARCHAR2(20) NOT NULL,
SG_APELLIDO VARCHAR2(20),
CONSTRAINT pk_actividad100 PRIMARY KEY(DNI));

create table A1_ASIGNATURA(
COD_ASIG NUMBER(4) PRIMARY KEY,
NOMBRE VARCHAR2(20) NOT NULL,
NUM_HORAS NUMBER(3) NOT NULL
);
CREATE TABLE INSCRIPCION(
DNI NUMBER(8),
COD_ASIG NUMBER(4),
CALIFICACION NUMBER(4,2),

CONSTRAINT PK_INSCRIPCCION PRIMARY KEY (DNI, COD_ASIG),
CONSTRAINT PK_INSCRIP_ALUM FOREIGN KEY (DNI) REFERENCES A1_ALUMNO(DNI),
CONSTRAINT PK_INSCRIP_ASIG FOREIGN KEY (COD_ASIG) references A1_ASIGNATURA(COD_ASIG)
);
     