create table A2_PROFESOR(
DNI NUMBER(8) NOT NULL,
NOMBRE VARCHAR2 (30) NOT NULL,
PR_APELLIDO VARCHAR2(20) NOT NULL,
SG_APELLIDO VARCHAR2(20),
DIRECCION VARCHAR2(20) NOT NULL,
CUENTA VARCHAR2(20) NOT NULL,
TELEFONO NUMBER(9) NOT NULL,
CONSTRAINT PK_A2_DNI PRIMARY KEY(DNI));

create table A2_CICLOFORM(
CODCICLO NUMBER(3) NOT NULL,
NOMBRE VARCHAR2(30) NOT NULL,
TIPO CHAR(5) NOT NULL,
CONSTRAINT PK_A2_CODCICLO PRIMARY KEY (CODCICLO));

CREATE TABLE A2_ASIGNATURA(
CODASIG NUMBER(8) NOT NULL,
NOMBRE VARCHAR2(30) NOT NULL,
NUMHORAS NUMBER(3) NOT NULL,
DNI NUMBER(8) NOT NULL,
CODCICLO NUMBER(3) NOT NULL,
CONSTRAINT PK_A2_CODASIG PRIMARY KEY(CODASIG),
CONSTRAINT FK_PROFESOR_ASIGNATURA FOREIGN KEY (DNI) REFERENCES A2_PROFESOR,
CONSTRAINT FK_CICLOFORM_ASIGNATURA FOREIGN KEY (CODCICLO) REFERENCES A2_CICLOFORM);

CREATE TABLE A2_IDIOMA(
CODIDIOMA NUMBER(3) NOT NULL,
DESCRIPCION VARCHAR2(100) NOT NULL,
CONSTRAINT PK_A2_IDIOMA PRIMARY KEY(CODIDIOMA));

CREATE TABLE A2_ALUMNO(
DNI NUMBER(8) NOT NULL,
NOMBRE VARCHAR2 (30) NOT NULL,
PR_APELLIDO VARCHAR2(20) NOT NULL,
SG_APELLIDO VARCHAR2(20),
DIRECCION VARCHAR2(20) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL,
TELEFONO NUMBER(9) NOT NULL,
CODIDIOMA NUMBER(3),
CONSTRAINT PK_A2_DNIALUMNO PRIMARY KEY (DNI),
CONSTRAINT FK_IDIOMA_ALUMNO FOREIGN KEY (CODIDIOMA) REFERENCES A2_IDIOMA);

CREATE TABLE A2_MATRICULA(
DNI NUMBER(8) NOT NULL,
CODASIG NUMBER(8) NOT NULL,
CONSTRAINT PK_A2_DNICODASIG PRIMARY KEY (DNI, CODASIG),
CONSTRAINT FK_MATRICULA_ALUMNO FOREIGN KEY (DNI) REFERENCES A2_ALUMNO,
CONSTRAINT FK_MATRICULA_ALUMNO FOREIGN KEY (CODASIG) REFERENCES A2_ASIGNATURA,

CREATE TABLE IDIOMASPROF (
CODIDIOMA NUMBER(3) NOT NULL,
DNI NUMBER(8) NOT NULL,
CONSTRAINT PK_A2_CODIDIOMAPROF PRIMARY KEY (CODIDIOMA),
CONSTRAINT PK_A2_DNIPROF PRIMARY KEY (DNI),
CONSTRAINT FK_A2_CODIDIOMAPROF FOREIGN KEY (CODIDIOMA) REFERENCES A2_IDIOMA,
CONSTRAINT FK_A2_DNIPROF FOREIGN KEY (DNI) REFERENCES A2_PROFESOR,














